### ISSUE TITLE
Unable to start indy test network

### ISSUE THREAD

**Issue by darkchylde** [hyperledger/indy-node#1624]
Followed the instructions provided in the README.md file to [start a test network](https://github.com/hyperledger/indy-node#how-to-install-a-test-network),

Following command failed to execute `./pool_start.sh 4 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5 10 9701`, below is the console output,

```
Creating pool
4 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5 10
Creating pool of 4 nodes with ips 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5
Creating a new node Node1 0.0.0.0 9701 0.0.0.0 9702
Setting up docker with systemd
The systemd cgroup hierarchy is already mounted at /sys/fs/cgroup/systemd.
Your Docker host is now configured for running systemd containers!
Building indybase
Sending build context to Docker daemon   34.3kB
Step 1/1 : FROM solita/ubuntu-systemd:16.04
 ---> ebf71084f672
Successfully built ebf71084f672
Successfully tagged indybase:latest
Building indycore for user 1000
Sending build context to Docker daemon   34.3kB
Step 1/13 : FROM indybase
 ---> ebf71084f672
Step 2/13 : ARG uid=1000
 ---> Using cache
 ---> 5bb1984e1a34
Step 3/13 : RUN apt-get update -y && apt-get install -y         git     wget    python3.5       python3-pip     python-setuptools       python3-nacl    apt-transport-https     ca-certificates
 ---> Using cache
 ---> 5fd2a788e057
Step 4/13 : RUN pip3 install -U         'pip<10.0.0'    setuptools
 ---> Using cache
 ---> 9b350415b376
Step 5/13 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
 ---> Using cache
 ---> cf28ce36c515
Step 6/13 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BD33704C
 ---> Using cache
 ---> 245d6fad4bed
Step 7/13 : RUN echo "deb https://repo.sovrin.org/deb xenial master" >> /etc/apt/sources.list
 ---> Using cache
 ---> dd3840bbfdb3
Step 8/13 : RUN echo "deb https://repo.sovrin.org/sdk/deb xenial master" >> /etc/apt/sources.list
 ---> Using cache
 ---> 4e09de1da87e
Step 9/13 : RUN useradd -ms /bin/bash -l -u $uid indy
 ---> Using cache
 ---> ec5d8907883f
Step 10/13 : RUN apt-get update -y && apt-get install -y indy-node libindy
 ---> Running in 376e9ed88430
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [518 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [2331 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1494 kB]
Get:8 https://repo.sovrin.org/deb xenial InRelease [28.4 kB]
Get:9 https://repo.sovrin.org/sdk/deb xenial InRelease [28.5 kB]
Get:10 https://repo.sovrin.org/deb xenial/master amd64 Packages [344 kB]
Get:11 https://repo.sovrin.org/sdk/deb xenial/master amd64 Packages [524 kB]
Fetched 5593 kB in 9s (614 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-node : Depends: indy-plenum (= 1.13.0~dev1024) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -y && apt-get install -y indy-node libindy' returned a non-zero code: 100
```

**Comment by joinDonk** [comment]
I also encountered the same problem. I downloaded the version number of the website and found that none of them could be used? Why?

**Comment by WadeBarnes** [comment]
@darkchylde, You resolved the issue?  If so please provide details.

**Comment by darkchylde** [comment]
> @darkchylde, You resolved the issue? If so please provide details.

Reopening again. Temporarily fixed the issue by using specific indy node (1.12.1~dev1172) and plenum (1.12.1~dev989) versions,

Updated the `core.ubuntu.dockerfile` present in the following path, `environment > docker > pool`

```
FROM indybase

ARG uid=1000

# Install environment
RUN apt-get update -y && apt-get install -y \ 
	git \
	wget \
	python3.5 \
	python3-pip \
	python-setuptools \
	python3-nacl \
	apt-transport-https \
	ca-certificates 
RUN pip3 install -U \ 
	'pip<10.0.0' \
	setuptools
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BD33704C
RUN echo "deb https://repo.sovrin.org/deb xenial master" >> /etc/apt/sources.list
RUN echo "deb https://repo.sovrin.org/sdk/deb xenial master" >> /etc/apt/sources.list
RUN useradd -ms /bin/bash -l -u $uid indy
RUN apt-get update -y && apt-get install -y indy-plenum=1.12.1~dev989 indy-node=1.12.1~dev1172 libindy
RUN pip3 install python3-indy
USER indy
WORKDIR /home/indy
```

**Comment by darkchylde** [comment]
@WadeBarnes This issue is related to #1621

**Comment by RedsAnDev** [comment]
Good day to all!

This issue still exist today (master branch),even after update suggested here https://github.com/hyperledger/indy-node/issues/1624#issuecomment-710126373

```bash

The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-plenum : Depends: python3-orderedset (= 2.0) but 2.0.3 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-pympler (= 0.5) but 0.8 is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -y && apt-get install -y indy-plenum=1.12.1~dev989 indy-node=1.12.1~dev1172 libindy' returned a non-zero code: 100
```

**Comment by pSchlarb** [comment]
Trying to start the testpool with the  pool_start.sh fails.

From the build of environment/docker/pool/node.init.ubuntu.dockerfile:

> Step 18/20 : RUN if [ ! -z "$ips" ] && [ ! -z "$nodenum" ] && [ ! -z "$nodecnt" ]; then generate_indy_pool_transactions --nodes $nodecnt --clients $clicnt --nodeNum $nodenum --ips "$ips"; fi
 ---> Running in f616600846be
ERROR:ursa.lib:_load_cdll: Can't load libursa: libursa.so: cannot open shared object file: No such file or directory
Generating keys for provided seed b'000000000000000000000000000Node1'
Init local keys for client-stack
Public key is HXrfcFWDjWusENBoXhV8mARzq51f1npWYWaA1GzfeMDG
Verification key is Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv
Init local keys for node-stack
Public key is HXrfcFWDjWusENBoXhV8mARzq51f1npWYWaA1GzfeMDG
Verification key is Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv
Traceback (most recent call last):
  File "/usr/local/bin/generate_indy_pool_transactions", line 19, in <module>
    getTxnOrderedFields(), ConfigHelper, NodeConfigHelper)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/test_network_setup.py", line 246, in bootstrapTestNodes
    config_helper_class, node_config_helper_class)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/test_network_setup.py", line 129, in bootstrapTestNodesCore
    _, verkey, blskey, key_proof = initNodeKeysForBothStacks(nd.name, keys_dir, nd.sigseed, override=True)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/keygen_utils.py", line 51, in initNodeKeysForBothStacks
    keys = initLocalKeys(node_stack_name, keys_dir, sigseed, use_bls=use_bls, override=override)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/keygen_utils.py", line 16, in initLocalKeys
    blspk, key_proof = init_bls_keys(keys_dir, name, sigseed) if use_bls \
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/keygen_utils.py", line 30, in init_bls_keys
    stored_pk, key_proof = bls_factory.generate_and_store_bls_keys(seed)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/bls_factory.py", line 23, in generate_and_store_bls_keys
    sk, pk, key_proof = self.generate_bls_keys(seed)
  File "/usr/local/lib/python3.5/dist-packages/plenum/bls/bls_crypto_factory.py", line 18, in generate_bls_keys
    sk, pk, key_proof = self._generate_raw_bls_keys(seed)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/bls_factory.py", line 41, in _generate_raw_bls_keys
    seed)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/indy_crypto/bls_crypto_indy_crypto.py", line 122, in generate_keys
    gen = IndyCryptoBlsUtils.bls_from_str(params.g, Generator)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/indy_crypto/bls_crypto_indy_crypto.py", line 42, in bls_from_str
    return cls.from_bytes(bts)
  File "/usr/local/lib/python3.5/dist-packages/ursa/bls.py", line 32, in from_bytes
    do_call(cls.from_bytes_handler, xbytes, len(xbytes), byref(c_instance))
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 17, in do_call
    err = getattr(_cdll(), name)(*args)
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 27, in _cdll
    _cdll.cdll = _load_cdll()
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 62, in _load_cdll
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 54, in _load_cdll
    res = CDLL(lib_name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libursa.so: cannot open shared object file: No such file or directory
The command '/bin/sh -c if [ ! -z "$ips" ] && [ ! -z "$nodenum" ] && [ ! -z "$nodecnt" ]; then generate_indy_pool_transactions --nodes $nodecnt --clients $clicnt --nodeNum $nodenum --ips "$ips"; fi' returned a non-zero code: 1

It seems that ursa is not installed in the environment/docker/pool/core.ubuntu.dockerfile.

**Comment by pSchlarb** [comment]
Pool started with the pool_start.sh script after adding ursa.
But it seems that the documentation is outdated. 
Opened  #1686 for that.

**Comment by WadeBarnes** [comment]
Closing this for now.  Please re-open is this continues to be any issue.

**Comment by manolaz** [comment]
nice
