### ISSUE TITLE
ERROR:ursa.lib:_load_cdll: Can't load libursa: libursa.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Gabisonfire** [hyperledger/indy-node#1639]
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:09 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Error message:

```
Step 18/20 : RUN if [ ! -z "$ips" ] && [ ! -z "$nodenum" ] && [ ! -z "$nodecnt" ]; then generate_indy_pool_transactions --nodes $nodecnt --clients $clicnt --nodeNum $nodenum --ips "$ips"; fi
 ---> Running in bcea4ec6bdb2
ERROR:ursa.lib:_load_cdll: Can't load libursa: libursa.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/generate_indy_pool_transactions", line 19, in <module>
    getTxnOrderedFields(), ConfigHelper, NodeConfigHelper)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/test_network_setup.py", line 246, in bootstrapTestNodes
    config_helper_class, node_config_helper_class)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/test_network_setup.py", line 129, in bootstrapTestNodesCore
    _, verkey, blskey, key_proof = initNodeKeysForBothStacks(nd.name, keys_dir, nd.sigseed, override=True)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/keygen_utils.py", line 51, in initNodeKeysForBothStacks
    keys = initLocalKeys(node_stack_name, keys_dir, sigseed, use_bls=use_bls, override=override)
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/keygen_utils.py", line 16, in initLocalKeys
    blspk, key_proof = init_bls_keys(keys_dir, name, sigseed) if use_bls \
  File "/usr/local/lib/python3.5/dist-packages/plenum/common/keygen_utils.py", line 30, in init_bls_keys
    stored_pk, key_proof = bls_factory.generate_and_store_bls_keys(seed)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/bls_factory.py", line 23, in generate_and_store_bls_keys
    sk, pk, key_proof = self.generate_bls_keys(seed)
  File "/usr/local/lib/python3.5/dist-packages/plenum/bls/bls_crypto_factory.py", line 18, in generate_bls_keys
    sk, pk, key_proof = self._generate_raw_bls_keys(seed)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/bls_factory.py", line 41, in _generate_raw_bls_keys
    seed)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/indy_crypto/bls_crypto_indy_crypto.py", line 122, in generate_keys
    gen = IndyCryptoBlsUtils.bls_from_str(params.g, Generator)
  File "/usr/local/lib/python3.5/dist-packages/crypto/bls/indy_crypto/bls_crypto_indy_crypto.py", line 42, in bls_from_str
    return cls.from_bytes(bts)
  File "/usr/local/lib/python3.5/dist-packages/ursa/bls.py", line 32, in from_bytes
    do_call(cls.from_bytes_handler, xbytes, len(xbytes), byref(c_instance))
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 17, in do_call
    err = getattr(_cdll(), name)(*args)
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 27, in _cdll
    _cdll.cdll = _load_cdll()
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 62, in _load_cdll
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ursa/lib.py", line 54, in _load_cdll
    res = CDLL(lib_name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libursa.so: cannot open shared object file: No such file or directory
```

This was done using `./pool_start.sh` located in  `/indy-node/environment/docker/pool`.

From my understanding, this has to do with the build image and not the host itself but I could be wrong. Any ideas?

Cheers

**Comment by Gabisonfire** [comment]
Fixed using https://github.com/hyperledger/indy-node/pull/1634/files
